"""empty message

Revision ID: 0249221fa194
Revises: 9cff1f7d064a
Create Date: 2025-06-09 16:46:48.821942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0249221fa194'
down_revision: Union[str, None] = '9cff1f7d064a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('article_contents_subsection_id_fkey', 'article_contents', type_='foreignkey')
    op.create_foreign_key(None, 'article_contents', 'subsections', ['subsection_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('subsections_status_id_fkey', 'subsections', type_='foreignkey')
    op.create_foreign_key(None, 'subsections', 'publication_statuses', ['status_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subsections', type_='foreignkey')
    op.create_foreign_key('subsections_status_id_fkey', 'subsections', 'publication_statuses', ['status_id'], ['id'])
    op.drop_constraint(None, 'article_contents', type_='foreignkey')
    op.create_foreign_key('article_contents_subsection_id_fkey', 'article_contents', 'subsections', ['subsection_id'], ['id'])
    # ### end Alembic commands ###
