"""empty message

Revision ID: 0d4e12cd3db4
Revises: 0249221fa194
Create Date: 2025-06-09 17:03:16.953914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d4e12cd3db4'
down_revision: Union[str, None] = '0249221fa194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subsections_section_id_fkey', 'subsections', type_='foreignkey')
    op.create_foreign_key(None, 'subsections', 'sections', ['section_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subsections', type_='foreignkey')
    op.create_foreign_key('subsections_section_id_fkey', 'subsections', 'sections', ['section_id'], ['id'])
    # ### end Alembic commands ###
