"""empty message

Revision ID: fd7d43422dbb
Revises: 5acc8743b5df
Create Date: 2025-05-06 15:13:01.372865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd7d43422dbb'
down_revision: Union[str, None] = '5acc8743b5df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_status_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_types', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_types', 'user_status_types', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_types', type_='foreignkey')
    op.drop_column('user_types', 'status_id')
    op.drop_table('user_status_types')
    # ### end Alembic commands ###
